name: NPCStatistics
version: '${project.version}'
main: com.bungoh.npcstatistics.NPCStatistics
api-version: 1.18

depend: [Citizens, Placeholder, HolographicDisplays]

authors: [Bungoh, BuildTools]
description: NPC Statistics for LearnSpigot SMP